apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  namespace: test
  labels:
    app: angular1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular1
  template:
    metadata:
      labels:
        app: angular1
    spec:
      containers:
        - name: angular1
          image: '010193/angular:v164'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities: {}
            privileged: false
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          stdin: true
          tty: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: docker
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
